{% set name = "nifty-infusion-python" %}
{% set version = "0.1.0" %}
#{% set sha256 = "b2ada6f86faf5c9032e8b1a7b8cc0dff68a229e90ad80b366f5564fec03caa17" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../
  #fn: nifty_infusion-{{ version }}.tar.gz
  #url: https://github.com/DerThorsten/nifty_infusion/archive/{{ version }}.tar.gz
  #sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - numpy
    - toolchain
    - cmake
    - xtensor-python
    - pybind11
    - nifty-infusion >=0.1.0
    #- boost-cpp
    #- qpbo >=0.3.9
    #- ad3-cpp >=2.5.1
    #- nifty-meta >=0.5.3
    #- nifty-tools >=0.3.5
  run:
    - numpy
    - nifty-infusion >=0.1.0
    #- qpbo >=0.3.9
    #- ad3-cpp >=2.5.1

test:
  imports:
    - nifty_infusion


about:
  home: https://github.com/DerThorsten/nifty_infusion
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'nifty-infusion'
  description: 'nifty-infusion'
  documentation_url:  https://github.com/DerThorsten/nifty_infusion
  dev_url: https://github.com/DerThorsten/nifty_infusion

extra:
  recipe-maintainers:
    - DerThorsten
